#!/usr/bin/env sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"


# LAUNCHERS
killall cleanfullscreen
cleanfullscreen &
#wal -i "$HOME/.local/bin/wallpapers/Future"
#source "$HOME/.cache/wal/colors.sh"
# xrandr --dpi 144

# pkill sxhkd
# pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &


# mpd >/dev/null 2>&1 &     # Music player daemon

# xsetroot -cursor_name left_ptr &   # Change cursor from default x shape

# xset r rate 300 50 &	# Speed xrate up

# #xrdb .Xresources &

# #picom --experimental-backends --shadow-exclude-reg '1920+0-0' --opacity-rule "85:class_g ='urxvt'" --opacity-rule "80:class_g = 'rofi'" --opacity-rule "90:class_g = 'Alacritty'" --inactive-opacity 1.00 --blur-background-exclude "class_g = 'slop'" -CGfF -o 0.70 -O 0.028 -I 0.028 -t 0 -l 0 -r 3 -D2 -m 1.00 &

# pkill setbg
# setbg &

# #pkill picom
# #picom -b --config ~/.config/picom.conf --experimental-backends &

# pkill dunst
# dunst &                                # notification daemon

# #pkill unclutter
# #unclutter &       # hide mouse pointer when idle

# pkill nm-applet
# nm-applet &        # networkmanager applet/wifi,ethernet settings

#pkill /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#zathura ~/.local/share/Magyarch-i3.pdf &
#pkill notify-send
#sleep 8s && notify-send 'Nyomja meg a Super+F1-et a használati utasításért.' -t 10000 &

#xset s off -dpms &

#pkill udiskie
#udiskie -a &
#conky -c ~/.config/conky/magyarch.conkyrc &

#redshift -l 47.162495:19.503304 -t 6000:3600 -g 0.8 -m randr -v &
#xrandr --output DP-0 --primary --mode 3840x2160 --pos 2160x0 \
#	--output HDMI-0 --auto --scale 2x2 --rotate left &

#pkill polybar
#(sleep 2s && $HOME/.config/polybar/launch.sh) &
# ----------------------------------------------------------------------------------------------


# Bspwm configs
bspc config border_width         5
bspc config window_gap           15
bspc config top_padding          40
bspc config bottom_padding       10
bspc config right_padding        10
bspc config left_padding         10
bspc config split_ratio          0.52


bspc config borderless_monocle    false  # no borders in monocle layout.
bspc config gapless_monocle       false  # no gaps in monocle layout.
bspc config single_monocle        true  # use monocle layout if there is only 1 window.
bspc config automatic_scheme alternate
bspc config center_pseudo_tiled   true
#bspc config initial_polarity second_child
bspc config initial_polarity second_child
bspc config focus_follows_pointer true
#bspc config external_rules_command $HOME/.config/bspwm/spotify_rules
#b#spc config external_rules_command $HOME/.local/bin/float.sh
#bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh
#bspc config remove_disabled_monitors true
#bspc config merge_overlapping_monitors true


# Moving foating windows
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# Border colors
bspc config normal_border_color $(awk '$1 ~ "background" { print $2 }' ~/.Xresources)
bspc config active_border_color $(awk '$1 ~ "color4" { print $2 }' ~/.Xresources)
bspc config focused_border_color $(awk '$1 ~ "color4" { print $2 }' ~/.Xresources)
#bspc config presel_feedback_color $(awk '$1 ~ "red" { print $2 }' ~/.Xresources)
#bspc config urgent_border_color $(awk '$1 ~ "$color8" { print $2 }' ~/.Xresources)


# Single monitor choice
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor  -d "☢️ " "🤬 " "⚒️ " "🍭 " "🎲 " "🎬 " "🔰 "  "🎯 " "📀 "
#bspc monitor -d "Web " "Chat " "Edit " "Music " "Tor " "Video " "Vbox " "File " "Float "
#bspc monitor -d "" "" "" "" "" "" "" "" ""  ""
#bspc monitor -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X"


# Dual monitor example
# bspc monitor DP-0 -d 1 3 4 5 6 7 8
# bspc monitor HDMI-0 -d 2
# bspc monitor DP-0 -s HDMI-0





# Open applications on specific workspaces
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a discord desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^2' follow=on
bspc rule -a Subl3 desktop='^3' follow=on
bspc rule -a Steam desktop='^4' state=fullscreen follow=on
bspc rule -a Vlc desktop='^7' state=fullscreen follow=on
bspc rule -a Pcmanfm desktop='^8' follow=on
bspc rule -a Spotify desktop='^9' follow=on
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Ulauncher  border=off
#bspc rule -a burp-StartBurp desktop='^9' state=floating follow=on
#bspc rule -a scpad sticky=on state=floating rectangle=1880x1000+940+500
#bspc rule -a ncmpcpp sticky=on state=floating rectangle=1880x1000+940+500

# Floating apps
bspc rule -a Gpick state=floating rectangle=1880x1000+940+500
bspc rule -a Lxappearance state=floating rectangle=1880x1000+940+500
bspc rule -a Pavucontrol state=floating rectangle=1880x1000+940+500
bspc rule -a Pcmanfm:Dialog state=floating
bspc rule -a Alacritty:Alacritty:News state=floating rectangle=1880x1000+940+500
bspc rule -a Alacritty:Alacritty:Music state=floating rectangle=1880x1000+940+500
#bspc rule -a Alacritty:Alacritty:FM state=floating rectangle=1880x1000+940+500
bspc rule -a Alacritty:Alacritty:scratchpad state=floating rectangle=1880x1000+940+500
bspc rule -a Sxiv state=floating rectangle=1880x1000+940+500
bspc rule -a mpv state=floating rectangle=1880x1000+940+500

# Manage apps
bspc rule -a polybar manage=off
bspc rule -a Screenkey manage=off
#bspc rule -a xfce4-panel manage=off

###########END####################################################################
