#!/bin/sh
# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# URLs will be directly handed to the browser.
# Anything else, it search it.
browser=${BROWSER:-brave}

pgrep -x dmenu && exit

choice=$(echo "🦆" | dmenu -i -c -g 1 -l 15 -nb '#1a1a1a' -nf '#c3cdc8' -sb '#9872bf' -fn 'JetBrains Mono Nerd Font:size=12' -p "Search DuckDuckGo:") || exit 1

if [ "$choice" = "🦆"  ]; then
    $browser "https://duckduckgo.com"
else
    if echo "$choice" | grep "^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$"; then
        $browser "$choice"
    else
        $browser "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
    fi
fi

