#!/bin/sh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "No\\nYes" | dmenu -i -c -g 1 -l 10 -nb '#282a36' -nf '#f8f8f2' -sb '#bd93f9' -fn 'JetBrains Mono Nerd Font:size=12' -p "$1" )" = "Yes" ] && $2
