#!/usr/bin/env bash

case "$1" in

	scratchpad) 		
        entry="alacritty -t scratchpad" 		
        ;;
	FM) 		
        entry="alacritty -t FM -e vifm"		
        ;;
    News)
        entry="alacritty -t News -e newsboat"
        ;;
    Music)
        entry="alacritty -t Music -e ncmpcpp"
        ;;
    Todo)
        entry="alacritty -t Todo -e noti.sh"
        ;;
    launchkeys)
        entry="alacritty -t launchkeys -e spectrwm-bindings.sh"
esac

xdotool search --onlyvisible --name "$1" windowunmap \
    || xdotool search --name "$1" windowmap \
    || $entry &

Footer
© 2023 GitHub, Inc.
Footer navigation


